spring:
  application:
    name: twdBFF
 

services:
  redis: 
    name: Redis-ma
  logstash:
    name: logstash-drain
    
uri:
  apigateway: https://twdapigateway-interpervasive-pianist.sk.kr.mybluemix.net
  login: /login
  freebill: /freebill
  main: /main

logging:
  level:
    org.springframework.web: ERROR
    kr.co.tworld: DEBUG
  pattern:
    console: ${spring.application.name} %d{yyyy:MM:dd} %-5level --- [%thread] %logger{35} / %msg %n

hystrix: 
  command: 
    default: 
      execution: 
        isolation:
          thread:
            timeoutInMilliseconds:  60000
        timeout:
          enabled: true
      circuitBreaker:
        enabled: true
  threadpool: 
    default:  
      coreSize: 10  